name: onboarding_plus
description: A new Flutter package for onboarding.
version: 0.0.1
homepage: https://github.com/erayhamurlu/onboarding_plus

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dots_indicator: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: